const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
let frames=[],listeners={},buttons={},draws=0;
const ctx=new Proxy({canvas:{width:960,height:540},createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),measureText:s=>({width:String(s).length*8})},{get:(o,k)=>k in o?o[k]:(...a)=>{draws++},set:(o,k,v)=>(o[k]=v,true)});
const elements={game:{width:960,height:540,getContext:()=>ctx,addEventListener(){}},hud:{textContent:''},start:{addEventListener:(t,f)=>buttons[t]=f}};
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/id="([^"]+)"/g)){elements[match[1]]??={textContent:''};}let hudText='';const hudKids=[];Object.defineProperty(elements.hud,'textContent',{get:()=>hudText+' '+['score','level','lives','status'].filter(k=>elements[k]).map(k=>elements[k].textContent).join(' ')+' '+hudKids.map(k=>k.textContent).join(' '),set:v=>hudText=String(v)});elements.hud.appendChild=x=>hudKids.push(x);elements.hud.append=(...xs)=>hudKids.push(...xs);let rng=1;const gameMath=Object.create(Math);gameMath.random=()=>{rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296};
const world={console,Math:gameMath,Date,performance:{now:()=>0},document:{createElement:()=>({textContent:'',style:{}}),getElementById:id=>elements[id]??null,addEventListener:(t,f)=>(listeners[t]??=[]).push(f)},Image:class {constructor(){this.naturalWidth=0;}},requestAnimationFrame:f=>frames.push(f),addEventListener:(t,f)=>(listeners[t]??=[]).push(f)};world.window=world;world.globalThis=world;
const sandbox=vm.createContext(world);
for(const file of ['levels.js','physics.js','game.js','renderer.js','main.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),sandbox,{filename:file,timeout:3000});
assert.equal(typeof world.DonkeyMonkey.createGame,'function');assert.equal(typeof world.DMRenderer.draw,'function');assert.equal(typeof buttons.click,'function');buttons.click();assert.ok(world.donkeyMonkeyState,'debug state bound after start');
function key(type,code){for(const cb of listeners[type]??[])cb({code,key:code==='Space'?' ':code,preventDefault(){}});}
let now=0;function tick(n){for(let i=0;i<n;i++){now+=1000/60;const pending=frames;frames=[];for(const f of pending)f(now);}}

const api=world.DonkeyMonkey,initialSeed=1;
const clone=g=>JSON.parse(JSON.stringify(g));const ordered=l=>[...l.ladders].sort((a,b)=>b.y-a.y);
function goal(g,route){const l=api.levels[g.levelIndex],lad=ordered(l)[route];return lad?{x:lad.x+lad.w/2-12,y:lad.y,lad}:{x:l.exit.x+4,y:l.exit.y+l.exit.h};}
function progress(g,route){const p=goal(g,route);if(p.lad&&Math.abs(g.x-p.x)<4&&g.y+32<=p.y+0.1)return route+1;return route;}
function baseInput(g,route){const p=goal(g,route);if(Math.abs(g.x-p.x)>3)return {[g.x<p.x?'right':'left']:true};if(p.lad&&g.y+32>p.y)return {up:true};return {};}
function score(s){if(s.g.status==='won')return 1e9;const p=goal(s.g,s.route);return s.g.levelIndex*100000+s.route*10000-Math.abs(s.g.x-p.x)-2*Math.max(s.g.y+32-p.y,0);}
function simulate(s,mode){rng=s.rng;const g=clone(s.g);let route=s.route,simTime=s.time;const inputList=[];for(let i=0;i<8;i++){route=progress(g,route);let input=baseInput(g,route);if(mode==='wait'||mode==='jumpWait')input={};if(mode==='retreat'){input={};const p=goal(g,route);input[g.x<p.x?'left':'right']=true;}if((mode==='jump'||mode==='jumpWait')&&i===0)input.jump=true;inputList.push(input);const old=g.levelIndex;const nextTime=simTime+1000/60;api.update(g,input,(nextTime-simTime)/1000);simTime=nextTime;if(g.lives<s.g.lives||g.status==='gameover')return null;if(g.levelIndex!==old)route=0;if(g.status==='won')break;}
 const out={g,route,rng,time:simTime,first:s.first||inputList};out.score=score(out);return out;}
let g=world.donkeyMonkeyState,route=0,actualRng=rng,frameCount=0;let held={};const inputs=[],transitions=[];const modes=['advance','jump','wait','jumpWait','retreat'];
while(g.status==='playing'&&frameCount<18000){let beam=[{g:clone(g),route,rng:actualRng,time:now,first:null}],best=null;for(let depth=0;depth<12;depth++){const next=[];for(const state of beam)for(const mode of modes){const n=simulate(state,mode);if(n)next.push(n);}if(!next.length)break;next.sort((a,b)=>b.score-a.score);const unique=new Map();for(const n of next){const k=[n.g.levelIndex,n.route,Math.round(n.g.x/10),Math.round(n.g.y/8),Math.round(n.g.vy/60)].join(':');if(!unique.has(k))unique.set(k,n);if(unique.size>=16)break;}beam=[...unique.values()];best=beam[0];if(best.g.status==='won')break;}
 if(!best)throw Error('No safe input sequence at '+JSON.stringify({frameCount,g,route}));rng=actualRng;for(const input of best.first){const old=g.levelIndex;route=progress(g,route);for(const [flag,code] of Object.entries({left:'ArrowLeft',right:'ArrowRight',up:'ArrowUp',down:'ArrowDown',jump:'Space'})){if(!!input[flag]!==!!held[flag])key(input[flag]?'keydown':'keyup',code);held[flag]=!!input[flag];}tick(1);g=world.donkeyMonkeyState;inputs.push(input);frameCount++;if(g.levelIndex!==old){route=0;transitions.push({level:g.levelIndex+1,frames:frameCount,lives:g.lives});}if(g.status!=='playing')break;}actualRng=rng;
 if(frameCount%480===0)console.log(JSON.stringify({frames:frameCount,level:g.levelIndex+1,route,x:g.x,y:g.y,lives:g.lives}));}
const result={seed:initialSeed,status:g.status,level:g.levelIndex+1,lives:g.lives,frames:frameCount,transitions,inputs};console.log(JSON.stringify({...result,inputs:inputs.length}));assert.equal(g.status,'won');

key('keydown','Enter');key('keyup','Enter');tick(1);assert.equal(world.donkeyMonkeyState.status,'playing');assert.equal(world.donkeyMonkeyState.levelIndex,0);assert.equal(world.donkeyMonkeyState.lives,3);console.log('PASS full live keyboard-handler playthrough and restart');
