$ErrorActionPreference = "Stop"
Write-Host "CodeStudio verwendet Visual Studio Code und Ollama."
Write-Host "Python 3.11+ ist nur fuer den Quellstart erforderlich."
Write-Host "Start: start.cmd oder python codestudio.py [Projektordner]"
Write-Host "Modell, Kontext und Projekttests in der CodeStudio-Seitenleiste einstellen."
Write-Host "Es werden keine Modelle geladen oder globalen Einstellungen geaendert."
